bashrc: update bpf check

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -103,13 +103,11 @@ invoice (){
         }' $2
 }
 
-checkbpf () {
-        echo -en "\0324\0303\0262\0241\02\0\04\0\0\0\0\0\0\0\0\0\0377\0377\0\0\01\0\0\0" | tcpdump -r - "$1" 2>/dev/null
-        if [ $? -eq 0 ]; then
-                echo "Valid Ethernet BPF: $?"
-        else
-                echo "Invalid Ethernet BPF: $?"
-        fi
+check_bpf() {
+  exp="\0324\0303\0262\0241\02\0\04\0\0\0\0\0\0\0\0\0\0377\0377\0\0\01\0\0\0"
+  valid="Valid Ethernet BPF"
+  invalid="Invalid Ethernet BPF!"
+  echo -en "$exp" | tcpdump -r - "$*" 2>/dev/null && echo "$valid" || echo "$invalid"
 }
 
 SSH_COMPLETE=( $(cat ~/.ssh/known_hosts | \
